format = "$username$hostname$all"

[username]
show_always = true
format = "[$user]($style)"
style_user = "bold blue"
style_root = "bold red"

[hostname]
ssh_only = false
format = "[@$hostname]($style) "
style = "bold blue"
