general {
  # run hyprlock only if not already running
  lock_cmd = pidof hyprlock || hyprlock
  # lock before sleep / suspend
  before_sleep_cmd = loginctl lock-session
  # ensure DPMS back on after waking
  after_sleep_cmd = hyprctl dispatch dpms on
}

# Dim screen after 5 min
listener {
  timeout = 300
  on-timeout = brightnessctl -s set 10
  on-resume = brightnessctl -r
}

# Lock screen after 10 min
listener {
  timeout = 600
  on-timeout = loginctl lock-session
}

# Turn screen off after 12 min
listener {
  timeout = 720
  on-timeout = hyprctl dispatch dpms off
  on-resume = hyprctl dispatch dpms on
}

# Optional: suspend after 30 min
listener {
  timeout = 1800
  on-timeout = systemctl suspend
}
